name: Build mdBooks

on:
  push:
    branches:
      - main
      - feat/landing-page
      - "**"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # determine_paths:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #     - name: Set matrix from input
  #       id: set-matrix
  #       run: |
  #         if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
  #           # If triggered manually, use the input paths
  #           PATHS="${{ github.event.inputs.paths }}"
  #         else
  #           # Default paths for push/PR events - adjust as needed (comma separated)
  #           PATHS="srd/1.0/de"
  #         fi
  #         # Convert comma-separated list to JSON array
  #         JSON_ARRAY=$(echo $PATHS | jq -R -c 'split(",") | map(trim)')
  #         echo "matrix={\"path\":$JSON_ARRAY}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ["srd/1.0/de"]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Build mdBook
        run: |
          echo "Building book in ${{ matrix.path }}"
          cd "${{ matrix.path }}"
          mdbook build

      - name: Set artifact name
        id: set-artifact-name
        run: |
          ARTIFACT_NAME="mdbook-$(echo "${{ matrix.path }}" | tr '/' '-')"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ matrix.path }}/book
          retention-days: 7
