name: Build mdBooks

on:
  push:
    branches:
      - main
      - feat/landing-page
      - "**"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        path: ["srd/1.0/de"]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Build mdBook
        run: |
          echo "Building book in ${{ matrix.path }}"
          cd "${{ matrix.path }}"
          mdbook build

      - name: Create public directory structure
        run: |
          # Extract version and language from matrix path (e.g., "srd/1.0/de")
          IFS='/' read -ra PATH_PARTS <<< "${{ matrix.path }}"
          VERSION="${PATH_PARTS[1]}"
          LANG="${PATH_PARTS[2]}"

          # Create the public directory structure
          mkdir -p "public/srd/$VERSION/$LANG"

          # Copy the built book to the public directory
          cp -r "${{ matrix.path }}/book/"* "public/srd/$VERSION/$LANG/"

          echo "Created public/srd/$VERSION/$LANG/ with built content"

      - name: Generate landing page
        run: |
          echo "Running generate_landing_page.py script"
          python script/generate_landing_page.py

      - name: Move landing page to public directory
        run: |
          if [ -f "script/index.html" ]; then
            echo "Moving generated index.html to public directory"
            cp script/index.html public/index.html
          else
            echo "Creating basic landing page"
            echo "<html><head><title>DH SRD Documentation</title></head><body><h1>DH SRD Documentation</h1><p>Select a book from the list:</p><ul>" > public/index.html
            for dir in public/*/; do
              if [ -d "$dir" ]; then
                dirname=$(basename "$dir")
                echo "<li><a href=\"$dirname/\">$dirname</a></li>" >> public/index.html
              fi
            done
            echo "</ul></body></html>" >> public/index.html
          fi

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          fi
          done

      - name: Generate landing page
        run: |
          echo "Running generate_landing_page.py script"
          python script/generate_landing_page.py

      - name: Move landing page to public directory
        run: |
          if [ -f "script/index.html" ]; then
            echo "Moving generated index.html to public directory"
            cp script/index.html public/index.html
          else
            echo "Creating basic landing page"
            echo "<html><head><title>DH SRD Documentation</title></head><body><h1>DH SRD Documentation</h1><p>Select a book from the list:</p><ul>" > public/index.html
            for dir in public/*/; do
              if [ -d "$dir" ]; then
                dirname=$(basename "$dir")
                echo "<li><a href=\"$dirname/\">$dirname</a></li>" >> public/index.html
              fi
            done
            echo "</ul></body></html>" >> public/index.html
          fi

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
